language: python
python:
  - "2.7"
# command to install dependencies
env:
  - DJANGO_VERSION=1.7.4
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - python setup.py -q install
# command to run tests
script: nosetests